name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: [2.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Run CI scripts
        run: bin/ci
